version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi:latest
dependencies:
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  system:
    - openssh-clients
    - sshpass
    - git
