version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt
additional_build_steps:
  prepend_base: |
    RUN dnf install -y vim git
  append_final: |
    COPY custom-scripts /opt/scripts
