---
- name: Create projects
  hosts: localhost
  become: false
  gather_facts: false

  tasks:
    - name: Fail if project name not supplied
      ansible.builtin.fail:
        msg: The project_root must be specified with the option -e
      when: project_root is not defined

    - name: Fail if project user not supplied
      ansible.builtin.fail:
        msg: The project_user must be specified with the option -e
      when: project_user is not defined

    - name: Create the project directory
      ansible.builtin.file:
        path: "{{ project_root }}"
        state: directory
        mode: '0755'

    - name: Create the standard project directories
      ansible.builtin.file:
        path: "{{ project_root }}/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - inventory
        - inventory/host_vars
        - inventory/group_vars
        - playbooks
        - roles
        - plugins/modules
        - plugins/filters

    - name: Create Project Configuration
      ansible.builtin.copy:
        dest: "{{ project_root }}/ansible.cfg"
        mode: '0755'
        content: |
          [defaults]
          inventory = ./inventory/hosts
          remote_user = {{ project_user }}
          host_key_checking = false

    - name: Create Project inventory Entry localhost and mac group
      ansible.builtin.copy:
        dest: "{{ project_root }}/inventory/hosts"
        mode: '0755'
        content: |
          localhost
          [mac]
          localhost

    - name: Create Project localhost Variables
      ansible.builtin.copy:
        dest: "{{ project_root }}/inventory/host_vars/localhost.yaml"
        mode: '0755'
        content: |
          ansible_connection: local
          ansible_python_interpreter: "/Users/john.angle/.local/pipx/venvs/ansible-core/bin/python"
