name: Build, test, and scan my-ee:base
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install ansible and ansible-navigator
      run: pip install ansible ansible-navigator

    - name: Build EE
      run: ansible-builder build --container-runtime=docker -t ${{ vars.DOCKER_USERNAME }}/my-ee:candidate

    - name: Scan Image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ vars.DOCKER_USERNAME }}/my-ee:candidate

    - name: Test image against localhost
      run: ansible-navigator run tests/test_localhost.yml --execution-environment-image ${{ vars.DOCKER_USERNAME }}/my-ee:candidate --mode stdout --pull-policy never --container-engine docker --container-options='--user=0'
